services:
    jupyter:
        image: lab3
        volumes:
            - ./:/Lab3and4
        env_file:
            - .env
        ports:
            - "8892:8888"
        networks: 
            - lab3network
    
    postgres:
        image: postgres:latest
        env_file:
            - .env
        volumes:
            - postgresdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - lab3network

volumes:
    postgresdata:

networks:
    lab3network: